# Chạy đơn lẻ detector service: docker compose up -d --build
services:
  detector:
    build: .
    image: harbor.tado.vn/inference-services/grpc-det-person:v2.0.0
    container_name: grpc_person_detector
    volumes:
      - ./app/models/yolo/trt:/app/models/yolo/trt
      - ./app/models/yolo/pytorch:/app/models/yolo/pytorch
    ports:
      - "50060:50060"
    environment:
      GRPC_PORT: 50060
      USE_TENSORRT: ${USE_TENSORRT:-false}
      CONF_THRESHOLD: ${CONF_THRESHOLD:-0.10}
      BATCH_SIZE: ${BATCH_SIZE:-8}
      BATCH_TIMEOUT_MS: ${BATCH_TIMEOUT_MS:-10}
    gpus: all
    restart: always
    networks:
      - grpc-net

networks:
  grpc-net:
    driver: bridge
